export const IMAGE_PATH = 'assets/images/'
export const IMAGE_ASSETS_PATH = {
  "developer": IMAGE_PATH+'developer.svg',
  "sql_relational_database_certificate": IMAGE_PATH+"1695188086402.jpeg",
  "sololearn_angular_certificate": IMAGE_PATH+"1695155352644.jpeg",
  "flux_reactjs_certificate": IMAGE_PATH+"1695158008515.jpeg",
  "github_management_certificate": IMAGE_PATH+"1695160766877.jpeg",
  "advanced_app_with_javascript_certificate": IMAGE_PATH+"1695171693154.jpeg",
  "google_analytics_certificate": IMAGE_PATH+"1695188224504.jpeg",
  "linkedin_web_development_certificate": IMAGE_PATH+"1695488334099.jpeg",
  "hackerrank_angular_certificate": IMAGE_PATH+"1696635892851.jpeg",
  "menu": IMAGE_PATH+"menu.png",
  "employee_self_serv": IMAGE_PATH+"employee_self_serv.png",
  "employee_self_serv_2": IMAGE_PATH+"employee_self_serv_2.png",
  "employee_self_serv_3": IMAGE_PATH+"employee_self_serv_3.png",
  "employee_self_serv_4": IMAGE_PATH+"employee_self_serv_4.png",
  "flutter_netflix_clone": IMAGE_PATH+"flutter_netflix_clone.png",
  "socialbook": IMAGE_PATH+"socialbook.png",
  "socialbook_2": IMAGE_PATH+"socialbook_2.png",
}
